services:
  - type: web
    name: resqnet
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    numInstances: 1
    autoDeployTrigger: commit
    envVars:
      - key: RESQ_DATABASE_URL
        sync: false
      - key: RESQ_STORAGE_URL
        value: https://krstkevsgutdiftxuodh.supabase.co
      - key: RESQ_STORAGE_SERVICE_KEY
        sync: false
      - key: RESQ_STORAGE_BUCKET
        value: resqnet-private
      - key: RESQ_SECURE_COOKIES
        value: "true"
      - key: RESQ_AI_MODE
        value: rules
      - key: RESQ_VOICE_ENABLED
        value: "false"
      - key: RESQ_BOOTSTRAP_ADMIN_EMAIL
        value: resqnet@gmail.com
      - key: RESQ_BOOTSTRAP_ADMIN_PASSWORD
        sync: false
      - key: RESQ_BOOTSTRAP_ADMIN_NAME
        value: RESQNET Administrator
